version: "3"

networks:
  web:
    external: true

services:
  traefik:
    image: "traefik:v2.3"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Web UI (enabled by --api.insecure=true)
    networks:
      - web
    volumes:
      - "./services/traefik/traefik.yml:/etc/traefik/traefik.yml" # Set the static configuration
      - "./services/traefik/config.yml:/etc/traefik/config.yml" # Set the dynamic configuration
      - "./services/traefik/keys/server-cert.crt:/etc/traefik/keys/server-cert.crt" # Set the certificate key
      - "./services/traefik/keys/server-key.key:/etc/traefik/keys/server-key.key" # Set the private key
      - "/var/run/docker.sock:/var/run/docker.sock" # Give access to the Docker socket
  
  webserver:
    image: httpd:latest
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.webserver.rule=Host(`webserver.localhost`)"
      - "traefik.http.services.webserver.loadbalancer.server.port=80"
      - "traefik.http.middlewares.basic-auth.basicauth.users=${BASIC_AUTH_PAIR:?Basic auth credential pair is missing}"
      - "traefik.http.routers.webserver.middlewares=basic-auth"
      - "traefik.http.routers.webserver.tls=true" # Enable TLS for secure traffic
    volumes:
      - "./services/webserver/html:/usr/local/apache2/htdocs"

  kali:
    build:
      context: ./services/kali
    networks:
      - default
    tty: true
    volumes:
      - "./services/kali:/usr/local/services/kali"
      - "./crypto-results:/usr/local/crypto-results"
    environment:
      - FE_CREDENTIALS=${BASIC_AUTH_PAIR:?Basic auth credential pair is missing}

  ubuntu:
    build:
      context: ./services/ubuntu
    networks:
      - default
    tty: true
    volumes:
      - "./services/ubuntu:/usr/local/services/ubuntu"
      - "./crypto-results:/usr/local/crypto-results"