version: "3"

networks:
  web:
    external: true

services:
  traefik:
    image: "traefik:v2.3"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Web UI (enabled by --api.insecure=true)
    networks:
      - web
    volumes:
      - "./services/traefik/traefik.yml:/etc/traefik/traefik.yml" # Set the static configuration
      - "./services/traefik/config.yml:/etc/traefik/config.yml" # Set the dynamic configuration
      - "./services/traefik/keys/ca-cert.pem:/etc/traefik/keys/ca-cert.pem" # Set the certificate key
      - "./services/traefik/keys/ca-cert.pem:/etc/traefik/keys/ca-key.pem" # Set the private key
      - "/var/run/docker.sock:/var/run/docker.sock" # Give access to the Docker socket
  
  webserver:
    image: httpd:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.webserver.rule=Host(`webserver.localhost`)"
      - "traefik.http.services.webserver.loadbalancer.server.port=80"
      - "traefik.http.middlewares.basic-auth.basicauth.users=${BASIC_AUTH_PAIR:?Basic auth credential pair is missing}"
      - "traefik.http.routers.webserver.middlewares=basic-auth"
      - "traefik.http.routers.webserver.tls=true" # Enable TLS for secure traffic
    volumes:
      # - "./services/traefik/keys/ca-cert.pem:/usr/local/apache2/conf/ssl/ca-cert.pem" # Set the certificate key
      # - "./services/traefik/keys/ca-cert.pem:/usr/local/apache2/conf/ssl/ca-key.pem" # Set the private key
      - "./services/webserver/html:/usr/local/apache2/htdocs"
      # - "./services/webserver/httpd-vhosts.conf:/usr/local/apache2/conf/httpd-vhosts.conf"

  kali:
    image: "kalilinux/kali-rolling:latest"
    tty: true
