# Use the Ubuntu base image
FROM ubuntu:22.04

# Update the package repository and install required packages
RUN apt-get upgrade -y \
    && apt-get update \
    && apt-get install -y libopenscap8 wget lsb-release bzip2
