api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  web:
    address: :80 # Create the HTTP entrypoint on port 80
    http:
      redirections: # HTTPS redirection (80 to 443)
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    network: "default" # Default network to use for connections to all containers.
  file:
    filename: /etc/traefik/config.yml