# Use the Kali Linux base image
FROM kalilinux/kali-rolling:latest

# Update the package repository and install required packages
RUN apt-get update \
    && apt-get install -y gnutls-bin gnupg curl john
